version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm audit

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analyze:
          requires:
            - "test"

